spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/zero_base
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_gmail_id@gmail.com
    password: your_gamil_password
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            
logging:
  level:
    root: info